### PR TITLE
FYTokenFactory

### PR DESCRIPTION
**Pull request by albertocuestacanada**
Having a FYTokenFactory reduces the deployment size of Wand, and provides a better separation of concerns.

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
Tests will pass once `tweak/remove-settle` is merged into this, I just messed up with the npm interface imports.

**Comment by albertocuestacanada** [comment]
Fixes #234

**Comment by aniemerg** [comment]
All the checks are failing?

**Comment by albertocuestacanada** [comment]
The checks were failing because I messed up with the interface imports via npm, once the other PRs were merged into this one, everything aligned again.

**Pull request merged**
