### PR TITLE
Migrate to yieldspace-tv

### PR DESCRIPTION
**Pull request by alcueca**
Only used for YieldSpaceMultiOracle, which doesn't have unit tests yet even.

### CODE REVIEW

**Comment by alcueca** [comment]
@devtooligan, any idea what's breaking here?

**Comment by devtooligan** [comment]
@alcueca Shot in the dark, but could it be because the yieldspace-tv repo is private?  Lemme know if you'd like me to spend more time looking into this.

**Comment by alcueca** [comment]
Ah, that sounds plausible, maybe it's time to make it public.

**Comment by alcueca** [comment]
@devtooligan, at some point we would need to merge this.

**Comment by alcueca** [comment]
Actually, this should be merged only when yieldspace-tv is live, until then we should keep it unmerged.

**Review by devtooligan — APPROVED** [review]
Performed a fairly quick visual review.   Mostly reviewed structure and detailed changes.  Did not do side-by-side comparisons of any of the files that were copy-pasted in

lgtm

**Pull request merged**
